#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# https://github.com/desktop/desktop/issues/12562#issuecomment-1153237769
case `uname` in
  *CYGWIN*|*MINGW*|*MSYS*)
    npx.cmd pretty-quick --staged # bug on Windows/Github Desktop: add `.cmd` extension fixes it
  ;;
  *)
    npx pretty-quick --staged
  ;;
esac
